apiVersion: v1
kind: Service
metadata:
  labels:
    app: test
  name: test
  namespace: one
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: test
  sessionAffinity: None
  type: ClusterIP
