# Secret where the old hub database configuration can be found for data migration
apiVersion: v1
kind: Secret
metadata:
  name: old-postgres-hub-configuration-secret
  namespace: aap
type: Opaque
stringData:
  database: "<database name>"
  host: "<ip or url>"
  password: "<password>"
  port: "<port>"
  username: "<username>"
